server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://39.106.70.195:7000/eureka
    register-with-eureka: false # 消费者不向服务端注册
spring:
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    mode: LEGACYHTML5
    encoding: utf-8
    cache: false
  resources:
    static-locations: classpath:/static/